### ISSUE TITLE
Norwegian Bokmål vs. Nynorsk

### ISSUE THREAD

**Issue by Remo** [punic/punic#106]
We currently support `nn` as the only Norwegian language:
https://github.com/punic/punic/blob/master/bin/build.php#L122

I have some doubts about that, because from what I can see Bokmål is spoken by more people:
_A 2005 poll indicates that 86.3% use primarily Bokmål as their daily written language, 5.5% use both Bokmål and Nynorsk, and 7.5% use primarily Nynorsk._
https://en.wikipedia.org/wiki/Norwegian_language

I don't know much about the languages there, but it seems to be that we should add `nb` or replace `nn` with `nb`. Is there anyone who knows more about that?

**Comment by stelgenhof** [comment]
Not sure if it helps, but just want to add my experience with this matter:

Ideally supporting all locales would be the solution :) In my project Yasumi (https://azuyalabs.github.io/yasumi/) I was facing the same question. At that time I decided to go for the language that is spoken by the majority, therefor using "nb_NO". 

All variants of the Norwegian language can be added in Yasumi if there is a need for it. (Until now, no issues or requests received).

**Comment by Remo** [comment]
Thanks! Not sure I'd always want to have all the languages, it adds quite a lot of files, but maybe we could have a light and a full version? Or do we leave that to the user and expect them to run the build scripts? If that's the case I'd add a note in the documentation.

**Comment by stelgenhof** [comment]
Yes, in Yasumi not all languages/translations are available however it is designed to cover all languages. If a user likes to add a (uncommon) language they can perfectly add that in their own environment.

**Comment by mlocati** [comment]
When #121 will be resolved, adding new languages will be very easy.
I'm closing this issue: let's continue the discussion in #121
