### ISSUE TITLE
More default locales in releases

### ISSUE THREAD

**Issue by falahati** [punic/punic#108]
Hey,

I know I can build with more locales, but it is a pain to maintain a fork for an open source project just to have one or two more locales in the default list.

May I suggest that you add at least the top 20 countries with most internet users?
http://www.internetworldstats.com/top20.htm

This makes more sense. Currently, you have 40 locales in the package and to have these 20 countries on the list you need to add less than 5 more locales.

I also suggest that you check out the top 10 languages used on the web:
http://www.internetworldstats.com/stats7.htm

For example, you are clearly missing the Malaysia.

Ultimately, PHP is a scripting language used mostly used in web, so there should be a logical reason for choosing the locales to bundle as default with this library.

All being said, I used your library in the last couple of days and I should say, well done and thanks for developing such a life-saving piece of code. This is actually the best library I could find that do not download or cache CLDR information while running and don't need curl, allow_url_fopen or similar functions.

**Comment by falahati** [comment]
Especially that means:
`id`: Indonesian
`en_NG`: English - Nigeria
`bn`: Bengali
'fa`: Farsi (Persian)
`fil`: Philippine
`ms`: Malaysia

**Comment by Remo** [comment]
It's similar to this https://github.com/punic/punic/issues/106
I'll discuss this with Michele, he's currently on vacation.

**Comment by Saeid-Ghadiri** [comment]
Hi Soroush,
The progress bar only develop for framework 3.5, Can Framework 4.5 not be used? I tried but could not get it. Is it possible to guide me?

**Comment by falahati** [comment]
@Saeid-Ghadiri 
Hey Saeid,
This is an issue on the "Punic" project. Consider posting your issue here:
https://github.com/falahati/CircularProgressBar/issues

@Remo While at it, any progress on this issue Remo?

**Comment by Remo** [comment]
@falahati there's more connected to it, see this discussion https://github.com/punic/punic/pull/107

**Comment by mlocati** [comment]
When #121 will be resolved, adding new languages will be very easy.
I'm closing this issue: let's continue the discussion in #121
