### ISSUE TITLE
punic-3.1.0/bin/build.sh missing, can't build additional language data.

### ISSUE THREAD

**Issue by Anonymoosed** [punic/punic#130]
Expected: Can build more language data.
Actual: Build script missing, can't build more language data.

punic-3.1.0/bin/build.sh build script is missing, and so "To keep the size of the package at a reasonable level, only data for a limited set of languages (about 40, defined here) is included by default. If you need more, you can build them yourself using the bundled build script." is incorrect in the documentation, as no actual build script is provided.

**Comment by mlocati** [comment]
The new CLI command to be used to add additional data is `bin/punic-data` (see these [release notes](https://github.com/punic/punic/releases/tag/3.0.0).

I'll update the docs. Thanks for pointing it out

**Comment by Anonymoosed** [comment]
Tried this:

```
$ ./punic-data --locale=ALL
Source location : https://punic.github.io/data
CLDR version    : latest available
Format version  : 1
Locales         : all
Output directory: /Volumes/Macintosh_HD/Emojitranslate/localization/punic-3.1.0/src/data
Fetching data state... done.
Determining the latest CLDR version... 32.0.1

The locale all is not supported.
```

**Comment by Anonymoosed** [comment]
Thanks. Tried this:

 ```
./punic-data --locale=ALL
Source location : https://punic.github.io/data
CLDR version    : latest available
Format version  : 1
Locales         : all
Output directory: /localization/punic-3.1.0/src/data
Fetching data state... done.
Determining the latest CLDR version... 32.0.1

The locale all is not supported.
```
Looks like it is ignoring the uppercase of ALL.

**Comment by Anonymoosed** [comment]
--help says:
`    You can use [ALL] (case-sensitive) to include all available locales.
    You can prepend a minus sign to substract specific locales: so for instance
    --locale=-it,-de
    means 'the default locales except Italian and German'.
    Likewise:
    --locale=ALL`

However, it isn't --locale=ALL, it really is --locale=[ALL]

**Comment by mlocati** [comment]
Fixed by https://github.com/punic/punic/pull/131 and https://github.com/punic/punic.github.io/commit/d0faf2cf627f020b2533d5fef4fef33d7de1cb3f
