### ISSUE TITLE
Punic ignores Draft Status

### ISSUE THREAD

**Issue by fbonzon** [punic/punic#141]
Each piece of CLDR data comes with a draft status. See: http://cldr.unicode.org/index/process

> approved (default if not specified)
> contributed
> provisional
> unconfirmed

Punic is currently reading all four.

IMHO, provisional and unconfirmed data should be ignored by default. Possibly, an additional parameter in Punic API could be added, to explicitly allow use of provisional or unconfirmed data.

**Comment by mlocati** [comment]
Punic uses the JSON data of CLDR, which does not contain draft statuses...

**Comment by fbonzon** [comment]
Strictly speaking, there is no "JSON data of CLDR". There is only one delivery in XML, and Punic uses the ldml2json tool provided within CLDR releases to convert from XML to JSON.

When you read its man page or code, one the available argument is:

    .add("draftstatus", 's', "(approved|contributed|provisional|unconfirmed)", "unconfirmed",
        "The minimum draft status of the output data")

Punic does not set it, thus gets default unconfirmed draft status as minimum, e.g. all available data.

Other libraries using CLDR I've seen use contributed as minimum draft status by default. I think this is reasonable default value, and suggest Punic does the same.

You may want to include more data, with provisional and unconfirmed status included, but it should be enabled explicitly by the user. Either rebuild the JSON data with desired minimum draft status, like you may already do now when you want to add more locales in Punic, or a more sophisticated mechanism, where a draft status parameter is available in PHP to specify desired level dynamically.

**Comment by spotman** [comment]
:+1: on this!

**Comment by mlocati** [comment]
In #156 I updated the data from "unconfirmed" to "contributed" draft status.

The [data repository](https://github.com/punic/data) too now contains only "contributed" data (we really can't add multiple draft statuses: it's already soooooo big).
For people wanting to use another draft status: simply clone the [`punic/data`](https://github.com/punic/data) repository, and build the data with the `punic-build-data` (or `punic-build-data-docker`) CLI commands by using the new `--draft-status` switch (which has a default value of `contributed`).
Then use the `punic-data` CLI command of the main punic repository to import that built data into punic.
