### ISSUE TITLE
telephoneCodeData removed from CLDR 34

### ISSUE THREAD

**Issue by mlocati** [punic/punic#159]
Follow up of https://github.com/punic/punic/issues/158#issuecomment-441018057

> I'd prefer copying the telephone data from CLDR 33 into future punic-data releases, rather than patching data from future CLDR releases back into to CLDR 33.

@c960657 I'd prefer to have an up-to-date reference data.
We simply need a list of territory code -> phone prefixes. Are you aware of such list that's reliable and up-to-date?

**Comment by c960657** [comment]
https://github.com/giggsey/libphonenumber-for-php has loads of phone number information.
