### ISSUE TITLE
[Feature Request] Address formatting + Required information for country address

### ISSUE THREAD

**Issue by ahukkanen** [punic/punic#165]
Many websites / online stores which have fields for address only show the required information for that particular country for filling in the address. In particular, this mostly concerns the state/provice/administrative area field which is not required by default in most countries.

I would suggest to add information in Punic for it to be able to tell the required fields for the country's address. This information can be fetched from Google's address data:
https://chromium-i18n.appspot.com/ssl-address

Definitions for the Google's data:
https://github.com/google/libaddressinput/wiki/AddressValidationMetadata

In the Google's data this can be found inside the `require` key for each country.

In addition, I think it would be great if Punic included the address formatting data, i.e. how to format the address string in each country. This can be also different depending on the country. That is also included in the Google's data inside the `fmt` key.

There is another project that already provides that but due to its external dependencies it may be difficult to install on some existing projects (you know which one):
https://github.com/commerceguys/addressing

I believe this would fit Punic's scope quite good as well.

---

There's no public licensing information for the data but the Java library itself is Apache License 2.0 and the specification page says "open-source address metadata". Here's also some discussion regarding the license (no official answer from Google but at least it can be expected to be under Apache License 2.0):
https://github.com/google/libaddressinput/issues/155

**Comment by mlocati** [comment]
Well, Punic is "just" a layer to let PHP projects use the Unicode CLDR data (http://cldr.unicode.org/cldr-features).

This is not completely true now because we also use data from libphonenumber, but that's because they removed the phone data from CLDR and I wanted to keep BC.

I'd avoid adding even more complexity to this project, given also that code offering ZIP/address formatting rules won't have much in common with the CLDR data...

So, what about starting a new project for what you are asking?

**Comment by ahukkanen** [comment]
Yeah, thought that might be the case.

I'll see if I can get around that installation issue in some other way then. I just thought this would have been a good fit here since it's also somewhat contry/localization specific feature.

**Comment by bojanz** [comment]
commerceguys/addressing has a single dependency: doctrine/collections. And it accepts any version of it. Why would that cause problems for projects?

**Comment by ahukkanen** [comment]
@bojanz The composer setup is somewhat weird'ish at https://github.com/concrete5/concrete5/. I don't know exactly why but got a bunch of errors running `composer require commerceguys/addressing`. It could be also something in my local composer setup but it didn't want install because of conflicts.

I have now gone through some hoops and got it installed also using their composer setup. I'll see if I can get it working.

**Comment by bojanz** [comment]
Okay, happy to help if there are improvements needed. I've tried to keep the dependency list light precisely to avoid these problems (we ourselves integrate it into Drupal, similar situation).

**Comment by mlocati** [comment]
I wish PHP could work like node: every package could then have its own dependencies...
