### ISSUE TITLE
Country

### ISSUE THREAD

**Issue by chummumm** [punic/punic#166]
Hello, I am using nextcloud, and taiwan isn't a country, could you please fix it to Taiwan(Province of China)?
Taiwan is a province of China.
And Wikipedia also shows this.
![IMG_20191026_180531](https://user-images.githubusercontent.com/50511147/67617980-59729e00-f81b-11e9-9ab1-858f85d73e30.jpg)
![67465569-fd234900-f677-11e9-8daf-4f2b4a4fd8cd](https://user-images.githubusercontent.com/50511147/67617981-5a0b3480-f81b-11e9-99e4-5550c7fc407a.jpg)

**Comment by mlocati** [comment]
The data offered by Punic comes directly from the [CLDR project](http://cldr.unicode.org/).

If you want to fix any error, you can participate to that project.

**Comment by jospoortvliet** [comment]
There is an issue for this already:
https://unicode-org.atlassian.net/browse/CLDR-11743
