### ISSUE TITLE
Request for additional Supplemental Data information

### ISSUE THREAD

**Issue by stelgenhof** [punic/punic#17]
Hi,

It would be great if also the supplemental data could be made available. In particular I am interested in:
- Region/Currency (Which currency is used by what territory during what period).
- TerritoryInfo (Population, GDP, etc.)

Thanks! Sacha

**Comment by stelgenhof** [comment]
Great! Would you be able to include currency data as well?

**Comment by mlocati** [comment]
- [x] Region/Currency (Which currency is used by what territory during what period).

Done! See [the 1.4.0 release notes](https://github.com/punic/punic/releases/1.4.0) and [punic.github.io](http://punic.github.io/docs/class-Punic.Currency.html)
