### ISSUE TITLE
Update to CLDR v37

### ISSUE THREAD

**Issue by PickJBennett** [punic/punic#171]
Hello, thank you for the amazing library! There's a new CLDR dataset at http://cldr.unicode.org/index/downloads/cldr-37 and another one coming out soon.

If there is a way to update the data manually myself, please let me know. Thank you! :)

**Comment by mlocati** [comment]
The most recent version uses CLDR 39

**Comment by PickJBennett** [comment]
Of course there is. You waited over a year to respond. 😂

**Comment by mlocati** [comment]
Yep! It took me too much time. The problem is that I have to maintain so many open source projects, and I have to follow my main job in order to pay my bills
