### ISSUE TITLE
Request for Measurement Data

### ISSUE THREAD

**Issue by stelgenhof** [punic/punic#24]
Would it be possible include measurement data as well (found in /supplementalData/measurementData)?

It would be great as I am building a library for each country and all their settings.

**Comment by mlocati** [comment]
I just released Punic 1.3.0: see the [release notes](https://github.com/punic/punic/releases/1.3.0) for what's included in this version.
I'm planning to add some more measurement systems-related functions and the papersize info contained in the supplementalData/measurementData section.

**Comment by stelgenhof** [comment]
Wow. That was quick! Thanks a lot for this. I might have more requests coming up :)

**Comment by mlocati** [comment]
I also added [\Punic\Unit::getCountriesWithMeasurementSystem()](http://punic.github.io/docs/class-Punic.Unit.html#_getCountriesWithMeasurementSystem)

**Comment by mlocati** [comment]
I also added support for paper-size info:
- Punic\Unit::getPaperSizeFor
- Punic\Unit::getCountriesWithPaperSize
See the docs for more info: http://punic.github.io/docs/class-Punic.Unit.html

**Comment by mlocati** [comment]
> I am building a library for each country and all their settings.

@stelgenhof I'm just curious: is it a publicly accessible library? Punic is gaining a great popularity: it's used by [concrete5](http://www.concrete5.org) and by [ownCloud](http://owncloud.org/)... Maybe others?

**Comment by stelgenhof** [comment]
@mlocati The library will become available in the shape of a RESTful API. I needed general country related information and had built first a part myself that would retrieve data from CLDR. Until I found Punic :). Now I'm refactoring everything to use Punic. Thanks again for the great work! It saves me a lot of time.
