### ISSUE TITLE
PHPUnit scripts to test performance

### ISSUE THREAD

**Issue by Remo** [punic/punic#32]
So far I never cared much about performance as it was never a requirement for me, but there's definitely quite some potential. 
1. Do we want to use a library to cache certain things across multiple requests? A static array improves things a lot, but only for a single request. Using something like https://github.com/tedious/Stash could improve things even more in real life situations.
2. What do you think about adding some PHPUnit scripts to test performance? I currently run each test function several times per call, seems to give me a pretty good indication. Only problem I currently have is the slightly weird test where we fetch the whole JSON file https://github.com/punic/punic/blob/master/tests/Plural/PluralTest.php#L25-L41 . I've vote to remove that with a data provider based test script. Also makes it nicer to test things as it runs much quicker.

**Comment by mlocati** [comment]
1. I don't know, we may try but we need to do this carefully. Surely we have to do some heavy test with and without stash

2. Yes, that would be great. But performance should be compared against something... Do you have some ideas on how could we compare performance results between different TravisCI runs?
About the loaded json: it's built by the script that "normalizes" the CLDR data: see https://github.com/punic/punic/blob/1.4.0/bin/build.php#L702

**Comment by LukasReschke** [comment]
> Do we want to use a library to cache certain things across multiple requests? A static array improves things a lot, but only for a single request. Using something like https://github.com/tedious/Stash could improve things even more in real life situations.

To consider here is that any cached entries needs to get purged after some sane time period and also after library updates (because the implementation may differ). Furthermore a unique prefix would be needed to prevent collisions.

Generally speaking, that would for us :+1:

> What do you think about adding some PHPUnit scripts to test performance? I currently run each test function several times per call, seems to give me a pretty good indication. 

We at ownCloud use https://blackfire.io/ for performance analysis. However, that is not integrated into our CI environment and performed by the single devs themselves once one stumbles across a slow method. – Not sure how an optimal integration in CI with whatever tool would look like. If have a reliable idea I'd be great to steal them for us as well ;-)

**Comment by LukasReschke** [comment]
Let's just take the following script as example:

```php
<?php

session_write_close();
require_once('./3rdparty/punic/punic/punic.php');


$time1 = microtime(true);

for ($i = 1; $i <= 1000000; $i++) {
	\Punic\Calendar::getWeekdayName(4);
}
$time2 = microtime(true);
echo 'time: ' . ($time2 - $time1);
```

This script requires more than 2 seconds to run on my local machine – that is way too much than it would deserve to. And the other methods in the calendar class are even slower than this one is :)

**Comment by mlocati** [comment]
Tomorrow I'l try with cachegrind to see where we can have performance problems
