### ISSUE TITLE
\Punic\Language::getName has undefined variables

### ISSUE THREAD

**Issue by LukasReschke** [punic/punic#38]
$script, $territory and $language are not defined

**Comment by mlocati** [comment]
They should be defined by https://github.com/punic/punic/blob/master/code/Language.php#L56

**Comment by LukasReschke** [comment]
Mhm… `extract()` is not really good coding style – let me think about alternatives

**Comment by Remo** [comment]
Return an array and use list to get the variables?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: Lukas ReschkeSent: Sunday, January 18, 2015 12:46To: punic/punicReply To: punic/punicSubject: Re: [punic] \Punic\Language::getName has undefined variables (#38)Mhm… extract() is not really good coding style – let me think about alternatives

—Reply to this email directly or view it on GitHub.

**Comment by mlocati** [comment]
See https://github.com/punic/punic/pull/43
