### ISSUE TITLE
nl locale returns array() for getTimezoneNameNoLocationSpecific

### ISSUE THREAD

**Issue by ontracker** [punic/punic#401]
It seems the `nl` locale currently returns an empty array instead of an empty string when any getTimezoneNameNoLocationSpecific has no value.

    $tz = new \DateTimeZone('Asia/Kathmandu');
    $locale = 'nl';
    var_dump(\Punic\Calendar::getTimezoneNameNoLocationSpecific($tz, 'short', '', $locale));

I have seen no other locale behave this way. And it doesn't adhere to the method signature.

**Comment by mlocati** [comment]
Yep, that should be an empty string. I'm checking this issue atm

**Comment by mlocati** [comment]
Thanks! This is fixed by https://github.com/punic/data/commit/c3441df9af446368acd028206599cdf551f1a097 and #413
