### ISSUE TITLE
Incorrect description of one year interval with locale "de"

### ISSUE THREAD

**Issue by schwarz-b5c** [punic/punic#411]
# Summary

Using package `punic/punic:3.6.0` to describe an interval of one year with a width of `long` and the locale `de` leads to an incorrect result, which is immediately apparent to any German native speaker.

# Reproduction

The following code prints the long description of an interval of one year in German:

``` php
$start = new \DateTimeImmutable();
$end = $start->add(new \DateInterval('P1Y'));
echo \Punic\Calendar::describeInterval($end, $start, 1, 'long', 'de'), PHP_EOL;
```

# Expected Result

The code above should print the following correct output:

```
1 Jahr
```

# Actual Result

The code above instead prints the following incorrect output:

```
1 Jahrs
```

# Discussion

This package sources its locale data from https://github.com/punic/data, which in turn is sourced from https://github.com/unicode-org/cldr.

Executing the following command in punic/data's repository shows that it already contains the incorrect locale data:

``` sh
$ php -r "echo (require 'docs/2/39/de/units.php')['long']['duration']['year']['one'], PHP_EOL;"
%1$s Jahrs
```

Inspecting unicode-org/cldr's repository shows that it contains the correct data: https://github.com/unicode-org/cldr/blob/651afecf9ccf1541a49306993e8210fa2209aa0b/common/main/de.xml#L8377 Therefore the error must be in punic/data's CLDR conversion. We can also see that unicode-org/cldr contains data for different grammatical cases (see also the table at https://de.wiktionary.org/wiki/Jahr). I would surmise that punic/data does not handle the grammatical cases correctly. It probably combines all grammatical cases, which makes the last one listed in the file win, which would be https://github.com/unicode-org/cldr/blob/651afecf9ccf1541a49306993e8210fa2209aa0b/common/main/de.xml#L8380, which is what is present in punic/data.

**Comment by mlocati** [comment]
Thanks! This is fixed by https://github.com/punic/data/commit/4ae1db6d5b989c40060f00a6d1e4b094e54286cb and #412
