### ISSUE TITLE
CLDR 44 support

### ISSUE THREAD

**Issue by andrey-helldar** [punic/punic#420]
At the end of October, version 44 of CLDR was released. Are there plans to add support for it?

**Comment by mlocati** [comment]
What's new?

**Comment by andrey-helldar** [comment]
### CLDR 44

- Unicode 15.1 additions. Made the regular additions and changes for a new release of Unicode, including names for new scripts, collation data for Han characters, etc.
- Digitally disadvantaged language coverage. Work began to improve DDL coverage, with the following DDL locales now having higher coverage levels:
  - Modern: Cherokee, Lower Sorbian, Upper Sorbian
  - Moderate: Anii, Interlingua, Kurdish, Māori, Venetian
  - Basic: Esperanto, Interlingue, Kangri, Kuvi, Kuvi (Devanagari), Kuvi (Odia), Kuvi (Telugu), Ligurian, Lombard, Low German, Luxembourgish, Makhuwa, Maltese, N’Ko, Occitan, Prussian, Silesian, Swampy Cree, Syriac, Toki Pona, Uyghur, Western Frisian, Yakut, Zhuang
- The coverage status determines how well languages are supported on laptops, phones, and other computing devices. In particular, qualifying at a Basic level is typically a requirement just for being selectable on phones as a language. Note that for each language there are typically multiple locales, so 90 languages at Modern coverage corresponds to more than 350 locales at that coverage.

See more: https://cldr.unicode.org/index/downloads/cldr-44


### CLDR 43

- In English, Türkiye is now the primary country name for the country code TR, and Turkey is available as an alternate. Other locales have been reviewed to see whether similar changes would be appropriate.
- Name for the new timezone Ciudad Juárez
- The bar for each coverage level increases each release. Faroese (fo) increased from Basic to Moderate, while Cherokee (chr), Lower Sorbian (dsb), and Upper Sorbian (hsb) dropped from Modern to Moderate.

See more: https://cldr.unicode.org/index/downloads/cldr-43#h.qobmda543waj

**Comment by mlocati** [comment]
Let's put it in other words: what do you need of the new CLDR version that's not currently available in Punic?

**Comment by andrey-helldar** [comment]
I think I understand the question now.

For example, calling the Foo method does not always return locale information:

<details>
  <summary>Show table</summary>

| For which locale I get the information | Which locale language to display the information in |
|:---:|:---:|
| af | oc |
| sq | oc |
| ar | oc |
| hy | oc |
| az | oc |
| eu | oc |
| be | oc |
| bn | oc |
| bs | oc |
| bg | oc |
| ca | oc |
| km | oc |
| hr | oc |
| cs | oc |
| da | oc |
| nl | oc |
| en | oc |
| et | oc |
| fi | oc |
| fr | oc |
| gl | oc |
| ka | oc |
| de | oc |
| el | oc |
| gu | oc |
| he | oc |
| hi | oc |
| hu | oc |
| is | oc |
| id | oc |
| it | oc |
| ja | oc |
| kn | oc |
| kk | oc |
| ko | oc |
| lv | oc |
| lt | oc |
| mk | oc |
| ms | oc |
| mr | oc |
| mn | oc |
| ne | oc |
| nb | oc |
| nn | oc |
| oc | oc |
| ps | oc |
| fa | oc |
| nn | tg |
| sc | tg |
| sw | tg |
| sc | uz_Cyrl |
</details>

At the same time, for other locales the necessary information is displayed.

I use the following code to retrieve the names:

```php
use Punic\Language;

class Cldr extends Integration
{
    public function get(string $locale, string $forLocale): ?string
    {
        $result = $this->find($locale, $forLocale);

        return $result === $locale ? null : $result;
    }

    protected function find(string $locale, string $forLocale): string
    {
        return Language::getName($locale, $forLocale);
    }
}
```

That is, if I request the Swahili name for Tajik, the response will be `sw` instead of `Swahili`. So I add a check to return `null` in case of a match and in this case use the English name as fallback.

In updates 43 and 44, I expect to see a fix for these shortcomings. Of course, if they have been fixed there.

And I also expect to see corrected country names, e.g. Turkey.

But I can't exactly check if these changes are there. I've spent a lot of time trying to figure out changelog and apparently I don't fully understand how it works. I also tried to collect data for the [punic/data](https://github.com/punic/data) project, but I couldn't - the JDK was installed, but then the console returned some unknown error:

```bash
$ ./bin/punic-data-builder data:build
Missing command: mvn
Unable to find the Maven settings file. You can create is by using the mvn:configure command.
```

I use the names of [locales](https://github.com/Laravel-Lang/native-locale-names), [countries](https://github.com/Laravel-Lang/native-country-names) and [currencies](https://github.com/Laravel-Lang/native-currency-names) in my projects.

And of the simplest, CLDR 42 displays the country name incorrectly - `Turkey` instead of `Türkiye`:

```php
return Territory::getName(Data::getTerritory('tr'), 'en');
// Turkey
```
