### ISSUE TITLE
Request for PostalCode Data

### ISSUE THREAD

**Issue by stelgenhof** [punic/punic#52]
Would it be possible to get the Postalcode data from postalCodeData.xml? I am interested also getting the regular expressions of the postcodes.

Thanks! Sacha

**Comment by bojanz** [comment]
Postal code data has been removed in CLDR v28: 
http://unicode.org/cldr/trac/ticket/8421

The data was based on a very early commit from Google's team. I'm maintaining a recent version (scrapped from their service endpoint) at https://github.com/commerceguys/addressing, feel free to steal it.

**Comment by stelgenhof** [comment]
Thanks for the update! Will have a look at your version.
