### ISSUE TITLE
hide Isle of Man and Jersey by default?

### ISSUE THREAD

**Issue by Remo** [punic/punic#70]
I wonder whether we should hide those two "countries" by default. Do people from those places want to select their place as a country? Would they pick UK? Isle of man doesn't belong to the UK.. Anyone who knows more about this than I do?

concrete5 removes those two entries:
http://concrete5.org/api/source-class-Concrete.Core.Localization.Service.CountryList.html#_loadCountries

**Comment by mlocati** [comment]
I've some doubts about removing territories in Punic.
1. I'm not sure if there are more territories to be removed
2. Punic isn't used/targeted to concrete5 only, it's *just* a wrapper to the CLDR data.

What about filtering territories in a concrete5 helper?

**Comment by Remo** [comment]
The concrete5 helper already filters those two countries.
I'm just asking myself what users of CLDR are expecting, would they expect to see Jersey or not?

If you ask me personally I'd have kept those two entries in concrete5 too since Jersey doesn't belong to the UK and I'd expect that a person living there wouldn't want to select UK as their country. I might be mistaked though, never been there nor do I know anything about those islands.

I wouldn't have removed them, maybe just an optional parameter ignoring them by default or the other way round.

**Comment by Remo** [comment]
I did google a bit, seems like this will be a never ending story. Worst case: Someone has two useless entries in the registration form..

**Comment by mlocati** [comment]
:+1:
