### ISSUE TITLE
Comparer exception if 'intl' not installed but using the symfony\collator.

### ISSUE THREAD

**Issue by olsgreen** [punic/punic#85]
If I try to create a new Comparer with a locale that is not 'en' and I do not have the 'intl' PHP extension installed but I do have the Symfony\Component\Intl\Collator\Collator loaded, I get an exception thrown when it could be handled gracefully.

An edge case that can be corrected externally, closing the issue, sorry!

**Comment by mlocati** [comment]
Why did you close this issue?

**Comment by olsgreen** [comment]
Because I'm a muppet! Reopened.

**Comment by mlocati** [comment]
Fixed by https://github.com/punic/punic/commit/c6a779cb0349948f093d40b9f6a4fe5c6f8a6a36
